import sys
from datetime import date


def iter_elf_symbols(f):
    from elftools.elf.elffile import ELFFile
    from elftools.elf.sections import SymbolTableSection

    elf = ELFFile(f)
    section = elf.get_section_by_name(".symtab")

    if section is None or not isinstance(section, SymbolTableSection):
        return

    for sym in section.iter_symbols():
        name = sym.name

        if (len(name) == 0) or ("$" in name) or ("." in name):
            continue

        yield (
            sym.entry.st_value,
            name,
            sym.entry.st_size,
            sym.entry.st_info.type == "STT_FUNC",
        )


def main(args):
    try:
        elfname = args[0]

    except IndexError:
        sys.exit("Usage: {} <ELF>".format(sys.argv[0]))

    with open(elfname, "rb") as f:
        elf_symbols = {
            addr: (name, size, is_func)
            for addr, name, size, is_func in iter_elf_symbols(f)
        }

    print("")

    print(f"# generated by elf2ref on {date.today()}")
    print("")

    addr_list = sorted(elf_symbols.keys())

    for addr in addr_list:
        if addr < 0x02000000 or addr > 0x0A000000:
            continue

        (name, size, is_func) = elf_symbols[addr]

        if is_func:
            # HACK that accounts for functions that end before a 2byte padding value
            if addr + size not in elf_symbols and addr + size + 2 in elf_symbols:
                size = size + 2

        print(f"{'fun' if is_func else 'dat'} 0x{addr:08X} {name} 0x{size:02X}")


if __name__ == "__main__":
    main(sys.argv[1:])
